---
on:
  release:
    types: [published]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger CircleCI publish-docs pipeline"
        id: react-native-mlkit-publish-docs
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: $
